Repository pythonkr/pyconkr, pull requests merged in 2020-09, with the labels that each got.

#149 시간표 추가
  program/admin.py
  program/migrations/0017_proposal_track_num.py
  program/models.py
  program/views.py
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/schedule.html
  pyconkr/templates/schedule_old.html
Labels: enhancement, important

#150 페이지 우측에 상단 이동 버튼 추가
  pyconkr/static/css/pyconkr-media.scss
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/footer.html
Labels: enhancement

#152 라이트닝 토크 홈 수정
  program/forms.py
  program/migrations/0018_auto_20200903_0019.py
  program/migrations/0019_auto_20200903_0019.py
  program/migrations/0020_auto_20200903_0023.py
  program/models.py
  program/views.py
  pyconkr/locale/en/LC_MESSAGES/django.po
  pyconkr/locale/ko/LC_MESSAGES/django.po
  pyconkr/settings.py
  pyconkr/templates/index.html
  pyconkr/templates/pyconkr/lightning_talk_home.html
  registration/locale/en/LC_MESSAGES/django.po
  registration/locale/ko/LC_MESSAGES/django.po
  sponsor/locale/en/LC_MESSAGES/django.po
  sponsor/locale/ko/LC_MESSAGES/django.po
  user/locale/en/LC_MESSAGES/django.po
  user/locale/ko/LC_MESSAGES/django.po
Labels: enhancement

#153 시간표, 키노트에 노출 조건 추가
  program/admin.py
  program/urls.py
  program/views.py
  pyconkr/locale/en/LC_MESSAGES/django.po
  pyconkr/locale/ko/LC_MESSAGES/django.po
  pyconkr/settings.py
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/pyconkr/keynote_list.html
  pyconkr/templates/schedule.html
  registration/locale/en/LC_MESSAGES/django.po
  registration/locale/ko/LC_MESSAGES/django.po
  sponsor/locale/en/LC_MESSAGES/django.po
  sponsor/locale/ko/LC_MESSAGES/django.po
  user/locale/en/LC_MESSAGES/django.po
  user/locale/ko/LC_MESSAGES/django.po
Labels: enhancement

#154 발표 시간표에 뱃지 추가
  program/views.py
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/schedule.html
Labels: enhancement

#155 시간표 마무리
  program/forms.py
  program/migrations/0021_auto_20200906_0131.py
  program/models.py
  program/urls.py
  program/views.py
  pyconkr/locale/en/LC_MESSAGES/django.po
  pyconkr/locale/ko/LC_MESSAGES/django.po
  pyconkr/settings.py
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/footer.html
  pyconkr/templates/pyconkr/keynote_list.html
  pyconkr/templates/schedule.html
  pyconkr/urls.py
  registration/locale/en/LC_MESSAGES/django.po
  registration/locale/ko/LC_MESSAGES/django.po
  registration/urls.py
  sponsor/locale/en/LC_MESSAGES/django.po
  sponsor/locale/ko/LC_MESSAGES/django.po
  sponsor/urls.py
  user/locale/en/LC_MESSAGES/django.po
  user/locale/ko/LC_MESSAGES/django.po
  user/urls.py
Labels: enhancement, major

#157 후원사용 계정 프로필에도 후원사 신청 내역 표시
  user/views.py
Labels: bug

#161 시간표 공개 이후 Proposal을 수정할 수 없음
  program/forms.py
  program/views.py
  pyconkr/templates/pyconkr/proposal_detail.html
Labels: bug

#162 LIVE 표시에 예외 추가
  program/views.py
Labels: bug

#163 라톡, 클로징 리다이렉트 수정
  program/views.py
  pyconkr/urls.py
Labels: enhancement

#164 발표 시간표, 키노트 페이지 수정
  program/views.py
  pyconkr/static/css/pyconkr-media.scss
  pyconkr/static/css/pyconkr.scss
Labels: bug

#165 Patron 리스트, admin 변경
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/pyconkr/patron_list.html
  registration/admin.py
  user/admin.py
Labels: bug, enhancement, minor

#168 Virtual booth 수정 마감 기한 추가
  pyconkr/settings.py
  sponsor/views.py
Labels: enhancement

#169 발표 영상 오픈 이전에 발표 영상을 확인할 수 있습니다.
  program/views.py
  pyconkr/locale/en/LC_MESSAGES/django.po
  pyconkr/locale/ko/LC_MESSAGES/django.po
  pyconkr/templates/pyconkr/program_detail.html
  registration/locale/en/LC_MESSAGES/django.po
  registration/locale/ko/LC_MESSAGES/django.po
  sponsor/locale/en/LC_MESSAGES/django.po
  sponsor/locale/ko/LC_MESSAGES/django.po
  user/locale/en/LC_MESSAGES/django.po
  user/locale/ko/LC_MESSAGES/django.po
  user/templates/user/profile_detail.html
Labels: enhancement

#170 Virtual booth 수정 가능 기간 변경
  program/slack.py
  sponsor/views.py
Labels: enhancement

#172 파준위 소개글 추가
  pyconkr/context_processors.py
  pyconkr/locale/en/LC_MESSAGES/django.po
  pyconkr/locale/ko/LC_MESSAGES/django.po
  pyconkr/static/css/pyconkr.scss
  pyconkr/urls.py
  registration/locale/en/LC_MESSAGES/django.po
  registration/locale/ko/LC_MESSAGES/django.po
  sponsor/locale/en/LC_MESSAGES/django.po
  sponsor/locale/ko/LC_MESSAGES/django.po
  user/admin.py
  user/locale/en/LC_MESSAGES/django.po
  user/locale/ko/LC_MESSAGES/django.po
  user/migrations/0010_staff.py
  user/migrations/0011_auto_20200918_2254.py
  user/migrations/0012_auto_20200918_2256.py
  user/migrations/0013_auto_20200918_2256.py
  user/migrations/0014_auto_20200918_2257.py
  user/models.py
  user/templates/user/staff_list.html
  user/translation.py
  user/views.py
Labels: enhancement

#173 영문 폰트 수정
  pyconkr/static/css/pyconkr-teaser.scss
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/base.html
Labels: enhancement

#175 Virtual booth 내용 전처리
  sponsor/views.py
Labels: enhancement

#177 페이지 캐싱 범위 수정
  program/urls.py
  pyconkr/templates/pyconkr/patron_list.html
  pyconkr/templates/pyconkr/program_list.html
  pyconkr/templates/schedule.html
  pyconkr/urls.py
Labels: bug

#178 프로필 이미지 개편
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/pyconkr/patron_list.html
  pyconkr/templates/pyconkr/program_list.html
  pyconkr/templates/pyconkr/sprint_list.html
  pyconkr/templates/schedule.html
  user/forms.py
  user/migrations/0015_auto_20200924_0949.py
  user/migrations/0016_auto_20200924_2200.py
  user/models.py
  user/templates/user/profile_detail.html
  user/templates/user/staff_list.html
Labels: enhancement, python

#180 Timeout 문제 해결
  mailing/signal.py
  mailing/thread.py
  requirements.txt
Labels: important

#181 Index 페이지에 LIVE 알림 추가
  pyconkr/locale/en/LC_MESSAGES/django.po
  pyconkr/locale/ko/LC_MESSAGES/django.po
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/index.html
  pyconkr/views.py
  registration/locale/en/LC_MESSAGES/django.po
  registration/locale/ko/LC_MESSAGES/django.po
  sponsor/locale/en/LC_MESSAGES/django.po
  sponsor/locale/ko/LC_MESSAGES/django.po
  user/locale/en/LC_MESSAGES/django.po
  user/locale/ko/LC_MESSAGES/django.po
Labels: enhancement

#182 라톡 리다이렉트 수정
  program/views.py
  pyconkr/urls.py
Labels: minor

#183 참가자 슬랙 초대 폼
  mailing/admin.py
  mailing/forms.py
  mailing/migrations/0004_newsletter_agree_coc.py
  mailing/models.py
  mailing/templates/slack_invitation_add.html
  mailing/views.py
  program/slack.py
  pyconkr/locale/en/LC_MESSAGES/django.po
  pyconkr/locale/ko/LC_MESSAGES/django.po
  pyconkr/settings.py
  pyconkr/templates/schedule.html
  pyconkr/urls.py
  registration/locale/en/LC_MESSAGES/django.po
  registration/locale/ko/LC_MESSAGES/django.po
  sponsor/locale/en/LC_MESSAGES/django.po
  sponsor/locale/ko/LC_MESSAGES/django.po
  user/locale/en/LC_MESSAGES/django.po
  user/locale/ko/LC_MESSAGES/django.po
Labels: enhancement
