Repository pythonkr/pyconkr, pull requests merged in 2020-08, with the labels that each got.

#102 Virtual booth 수정
  pyconkr/static/css/pyconkr.scss
  sponsor/templates/sponsor/virtual_booth_home.html
  sponsor/views.py
Labels: minor

#103 Virtual booth 개선
  pyconkr/static/css/pyconkr.scss
  sponsor/templates/sponsor/virtual_booth_home.html
  user/templates/user/profile_detail.html
Labels: enhancement, minor

#104 Virtual booth 개편에 따른 번역 수정
  pyconkr/locale/en/LC_MESSAGES/django.po
  pyconkr/locale/ko/LC_MESSAGES/django.po
  registration/locale/en/LC_MESSAGES/django.po
  registration/locale/ko/LC_MESSAGES/django.po
  sponsor/locale/en/LC_MESSAGES/django.po
  sponsor/locale/ko/LC_MESSAGES/django.po
  sponsor/templates/sponsor/virtual_booth_home.html
  user/locale/en/LC_MESSAGES/django.po
  user/locale/ko/LC_MESSAGES/django.po
Labels: minor

#105 하단 CoC 링크 번역
  pyconkr/locale/en/LC_MESSAGES/django.po
  pyconkr/locale/ko/LC_MESSAGES/django.po
  pyconkr/templates/base.html
  registration/locale/en/LC_MESSAGES/django.po
  registration/locale/ko/LC_MESSAGES/django.po
  sponsor/locale/en/LC_MESSAGES/django.po
  sponsor/locale/ko/LC_MESSAGES/django.po
  user/locale/en/LC_MESSAGES/django.po
  user/locale/ko/LC_MESSAGES/django.po
Labels: important, minor

#106 Virtual booth 가독성 개선
  pyconkr/static/css/pyconkr.scss
  sponsor/templates/sponsor/virtual_booth_home.html
  sponsor/views.py
Labels: minor

#109 settings.py의 오타 수정
  pyconkr/settings.py
Labels: bug

#114 후원사 로그인 번역 추가, 버튼 수정
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/login.html
  sponsor/templates/sponsor/sponsor_login_form.html
Labels: minor

#115 홈 화면에 버튼 추가
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/index.html
Labels: enhancement

#116 후원사 로그인, 홈 화면 번역 추가
  pyconkr/locale/en/LC_MESSAGES/django.po
  pyconkr/locale/ko/LC_MESSAGES/django.po
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/index.html
  pyconkr/templates/login.html
  registration/locale/en/LC_MESSAGES/django.po
  registration/locale/ko/LC_MESSAGES/django.po
  sponsor/locale/en/LC_MESSAGES/django.po
  sponsor/locale/ko/LC_MESSAGES/django.po
  sponsor/templates/sponsor/sponsor_login_form.html
  user/locale/en/LC_MESSAGES/django.po
  user/locale/ko/LC_MESSAGES/django.po
Labels: minor

#119 홈 화면 버튼 모바일 대응 수정
  pyconkr/static/css/pyconkr-media.scss
Labels: minor

#118 후원사를 위한 아이디 마무리 작업
  sponsor/admin.py
  sponsor/locale/ko/LC_MESSAGES/django.po
  sponsor/migrations/0004_auto_20200814_1807.py
  sponsor/models.py
  sponsor/views.py
Labels: enhancement

#121 티켓 구매 기능
  program/admin.py
  program/forms.py
  program/models.py
  program/translation.py
  program/urls.py
  program/views.py
  pyconkr/context_processors.py
  pyconkr/locale/en/LC_MESSAGES/django.po
  pyconkr/locale/ko/LC_MESSAGES/django.po
  pyconkr/settings.py
  pyconkr/static/css/pyconkr-teaser.scss
  pyconkr/static/css/pyconkr.scss
  pyconkr/urls.py
  pyconkr/views.py
  registration/__init__.py
  registration/admin.py
  registration/apps.py
  registration/forms.py
  registration/iamporter/__init__.py
  registration/iamporter/iamporter.py
  registration/management/__init__.py
  registration/management/commands/__init__.py
  registration/management/commands/calculation_attendee.py
  registration/management/commands/delete_login_token.py
  registration/management/commands/payment_reconciliation.py
  registration/migrations/0002_auto_20200816_1624.py
  registration/models.py
  registration/signal.py
  registration/static/js/payment.js
  registration/templates/registration/cancellation_result.html
  registration/templates/registration/certificates.html
  registration/templates/registration/certificates_not_registered.html
  registration/templates/registration/certificates_not_visited.html
  registration/templates/registration/certificates_sprint.html
  registration/templates/registration/certificates_sprint_not_registered.html
  registration/templates/registration/certificates_tutorial.html
  registration/templates/registration/certificates_tutorial_not_registered.html
  registration/templates/registration/certificates_tutorial_not_visited.html
  registration/templates/registration/checkin_list.html
  registration/templates/registration/info.html
  registration/templates/registration/issue_print.html
  registration/templates/registration/issue_ticket.html
  registration/templates/registration/manual_payment.html
  registration/templates/registration/payment.html
  registration/templates/registration/payment_babycare.html
  registration/templates/registration/payment_youngcoder.html
  registration/templates/registration/registration_buy_ticket.html
  registration/templates/registration/registration_detail.html
  registration/templates/registration/registration_list.html
  registration/templates/registration/sprint_checkin.html
  registration/templates/registration/sprint_print.html
  registration/templates/registration/status.html
  registration/templates/registration/ticket_list.html
  registration/urls.py
  registration/views.py
  user/templates/user/profile_detail.html
  user/views.py
Labels: enhancement, important

#131 BCC를 이용한 메일 대량전송 대응
  mailing/signal.py
Labels: enhancement

#132 개인 후원자 페이지
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/pyconkr/patron_list.html
  pyconkr/urls.py
  registration/admin.py
  registration/migrations/0005_auto_20200824_1322.py
  registration/migrations/0006_ticket_price.py
  registration/migrations/0007_auto_20200825_1004.py
  registration/models.py
  registration/templates/registration/registration_buy_ticket.html
  registration/views.py
  user/forms.py
Labels: enhancement

#142 발표 상세 페이지 수정
  pyconkr/static/css/pyconkr.scss
  pyconkr/templates/pyconkr/program_detail.html
  pyconkr/templates/pyconkr/program_list.html
Labels: bug

#144 Virtual booth home의 출력 조건 변경
  sponsor/views.py
Labels: bug

#145 Feature/registration
  mailing/helper.py
  mailing/migrations/0003_auto_20200830_0923.py
  registration/admin.py
  registration/migrations/0008_ticket_agree_coc.py
  registration/models.py
  registration/signal.py
  registration/views.py
  sponsor/admin.py
  user/views.py
Labels: enhancement

#148 구독 해지 기능
  mailing/templates/newsletter_add.html
  mailing/templates/newsletter_remove.html
  mailing/templates/newsletter_remove_confirm.html
  mailing/views.py
  pyconkr/templates/pyconkr/newsletter_add.html
  pyconkr/urls.py
  sponsor/views.py
Labels: enhancement
